version: '3.3'

services:
  db:
    env_file:
      - .env
    container_name: django_db
    image: postgres
    volumes:
      - /home/django_db:/var/lib/postgresql/data:rw
  web:
    build: .
    image: django
    container_name: django_drf
    env_file:
      - .env
    volumes:
      - /home/django_drf:/home/abdullah
    depends_on:
      - db
    ports:
      - "8866:8866"
  