# Generated by Django 4.2.4 on 2023-08-30 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('type', models.CharField(choices=[('S', 'Şahıs'), ('BI', 'Büyük İşletme'), ('K', 'KOBİ'), ('STK', 'STK')], max_length=3)),
                ('country', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('employees', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Kurulus',
                'db_table': 'kurulus',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscribe_kurulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.kurulus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscribe',
                'db_table': 'subscribe',
            },
        ),
    ]
