# Generated by Django 4.2.4 on 2023-08-30 14:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurulus',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
